# Generated by Django 5.2.9 on 2025-12-12 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('salas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['data', 'status'], name='agendamento_data_36cd43_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['usuario', 'status'], name='agendamento_usuario_d488a5_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['sala', 'data', 'status'], name='agendamento_sala_id_7696f4_idx'),
        ),
    ]
